# Name of the GitHub Actions workflow
name: Playwright Github Actions

# Define when to trigger this workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs to run in this workflow
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Install Chrome browser for Playwright
        run: npx playwright install chrome

      - name: Run tests
        run: npm run test:serial
        env:
          npm_config_ENV: "qa"

      - name: Wait for job completion
        run: sleep 10s
        if: always()

      - name: Check if HTML report exists
        run: |
          if [ -d "html-report" ]; then
            echo "HTML report exists."
          else
            echo "HTML report does not exist. Exiting..."
            exit 1
          fi
        if: always()

      - name: Zip HTML report
        run: zip -r html-report.zip html-report
        if: always()

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: html-report.zip
          if-no-files-found: error
        if: always()

      - name: Generate artifact link
        id: artifact_link
        run: echo "artifact_url=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> "$GITHUB_OUTPUT"
        if: always()

      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: "#playwright-test-reports"
          SLACK_USERNAME: Playwright GitHub Actions
          SLACK_MESSAGE: "Test results are available in [Artifacts section](${{ steps.artifact_link.outputs.artifact_url }}) as html-report."
        if: always()
