# azure-pipelines.yml
trigger:
  - main  # Or your branch name

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: StorageSecrets
- name: AZURE_STORAGE_ACCOUNT_NAME
  value: 'playwrighttestresultsnm'
- name: CONTAINER_NAME
  value: 'allure-reports'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      npm ci
      npx playwright install --with-deps
    displayName: 'Install dependencies and browsers'

  - script: |
      npx playwright test tests/functional/BurnsMcDonnellHeaderFooter.test.ts
    displayName: 'Run specific Playwright test'

  - script: npx allure generate allure-results --clean -o allure-report
    displayName: 'Generate Allure Report'
    condition: always()

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'allure-report'
      artifact: 'allure-report'
    displayName: 'Publish Allure Report Artifact'
    condition: always()

  - task: AzureCLI@2
    displayName: 'Upload Allure Report to Blob Storage'
    inputs:
      azureSubscription: 'playwright-storage-connection'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        echo "Uploading Allure Report to Blob..."
        az storage blob upload-batch \
          --account-name $(AZURE_STORAGE_ACCOUNT_NAME) \
          --account-key $(AZURE_STORAGE_ACCOUNT_KEY) \
          --destination $(CONTAINER_NAME) \
          --source allure-report
    condition: always()
