# azure-pipelines.yml
trigger:
  - main  # Or your branch name

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: StorageSecrets
- name: AZURE_STORAGE_ACCOUNT_NAME
  value: 'playwrighttestresultsnm'
- name: CONTAINER_NAME
  value: 'allure-reports'
- name: REPORT_FOLDER
  value: 'allure-report-$(Build.BuildId)'  # Unique folder for every run

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      npm ci
      npx playwright install --with-deps
    displayName: 'Install dependencies and browsers'

  - script: |
      npx playwright test
    displayName: 'Run Playwright test'
    env:
      npm_config_ENV: qa

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/results.xml'
    displayName: 'Publish JUnit results to Azure Pipelines'

  - script: |
      curl -X POST \
        -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjb250ZXh0Ijp7ImJhc2VVcmwiOiJodHRwczovL3NsYW1wdGVjaC5hdGxhc3NpYW4ubmV0IiwidXNlciI6eyJhY2NvdW50SWQiOiI3MTIwMjA6NTIyNjg2NzgtMDhjMC00NDhjLTg4NTUtMmQzNTU5ODg5OWQxIiwidG9rZW5JZCI6ImRiMjAwODU3LTAxMDQtNGY1Yi04NTliLTE3Yjg0NWM1NDViOCJ9fSwiaXNzIjoiY29tLmthbm9haC50ZXN0LW1hbmFnZXIiLCJzdWIiOiI2M2E4NTEwOC1jMmI5LTNlZDAtYjc2NS1iMTIzMjVkOTQ4ZmUiLCJleHAiOjE3ODM0NjkyNDQsImlhdCI6MTc1MTkzMzI0NH0.sxFSV2ffesJ_-vTOTEItTZkI7c0WtBSHD_tiqJrkHwo" \
        -H "Content-Type: multipart/form-data" \
        -F "file=@results.xml" \
        "https://api.zephyrscale.smartbear.com/v2/automations/executions/junit?projectKey=SCRUM"
    displayName: Upload to Zephyr

  - script: npx allure generate allure-results --clean -o $(REPORT_FOLDER)
    displayName: 'Generate Allure Report'
    condition: always()

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(REPORT_FOLDER)'
      artifact: 'allure-report'
    displayName: 'Publish Allure Report Artifact'
    condition: always()

  - task: AzureCLI@2
    displayName: 'Upload Allure Report to Blob Storage'
    inputs:
      azureSubscription: 'playwright-storage-connection'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        echo "Uploading Allure Report to Blob..."
        az storage blob upload-batch \
          --account-name $(AZURE_STORAGE_ACCOUNT_NAME) \
          --account-key $(AZURE_STORAGE_ACCOUNT_KEY) \
          --destination $(CONTAINER_NAME)/$(REPORT_FOLDER) \
          --source $(REPORT_FOLDER)

        echo "✅ Allure Report uploaded!"
        echo "🔗 Report URL:"
        echo "https://$(AZURE_STORAGE_ACCOUNT_NAME).blob.core.windows.net/$(CONTAINER_NAME)/$(REPORT_FOLDER)/index.html"
    condition: always()

  - script: |
      echo "Sending Teams notification..."
      curl -H 'Content-Type: application/json' \
        -d '{
          "title": "Playwright Allure Report",
          "text": "✅ Test execution completed. [View Allure Report](https://$(AZURE_STORAGE_ACCOUNT_NAME).blob.core.windows.net/$(CONTAINER_NAME)/$(REPORT_FOLDER)/index.html)"
        }' \
      $(TEAMS_WEBHOOK_URL)
    displayName: 'Send Allure Report Link to Teams'
    condition: always()
