# azure-pipelines.yml

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

container:
  image: mcr.microsoft.com/playwright:v1.53.2-jammy

variables:
- group: StorageSecrets
- name: AZURE_STORAGE_ACCOUNT_NAME
  value: 'playwrighttestresultsnm'
- name: CONTAINER_NAME
  value: 'allure-reports'
- name: REPORT_FOLDER
  value: 'allure-report-$(Build.BuildId)'  # Unique folder for every run

steps:
  - script: |
      npm ci
    displayName: 'Install project dependencies'

  - script: |
      npx playwright test
    displayName: 'Run Playwright tests'
    env:
      npm_config_ENV: qa

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/results.xml'
    displayName: 'Publish JUnit results to Azure Pipelines'
    condition: always()

  - script: |
      curl -X POST \
        -H "Authorization: Bearer $(ZEPHYR_TOKEN)" \
        -H "Content-Type: multipart/form-data" \
        -F "file=@results.xml" \
        "https://api.zephyrscale.smartbear.com/v2/automations/executions/junit?projectKey=SCRUM"
    displayName: 'Upload to Zephyr'
    condition: always()

  - script: |
      npx allure generate allure-results --clean -o $(REPORT_FOLDER)
    displayName: 'Generate Allure Report'
    condition: always()

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(REPORT_FOLDER)'
      artifact: 'allure-report'
    displayName: 'Publish Allure Report Artifact'
    condition: always()

  - task: AzureCLI@2
    displayName: 'Upload Allure Report to Blob Storage'
    inputs:
      azureSubscription: 'playwright-storage-connection'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        echo "Uploading Allure Report to Blob..."
        az storage blob upload-batch \
          --account-name $(AZURE_STORAGE_ACCOUNT_NAME) \
          --account-key $(AZURE_STORAGE_ACCOUNT_KEY) \
          --destination $(CONTAINER_NAME)/$(REPORT_FOLDER) \
          --source $(REPORT_FOLDER)

        echo "✅ Allure Report uploaded!"
        echo "🔗 Report URL:"
        echo "https://$(AZURE_STORAGE_ACCOUNT_NAME).blob.core.windows.net/$(CONTAINER_NAME)/$(REPORT_FOLDER)/index.html"
    condition: always()

  - script: |
      echo "Sending Teams notification..."
      curl -H 'Content-Type: application/json' \
        -d '{
          "title": "Playwright Allure Report",
          "text": "✅ Test execution completed. [View Allure Report](https://$(AZURE_STORAGE_ACCOUNT_NAME).blob.core.windows.net/$(CONTAINER_NAME)/$(REPORT_FOLDER)/index.html)"
        }' \
      $(TEAMS_WEBHOOK_URL)
    displayName: 'Send Allure Report Link to Teams'
    condition: always()
